const {chromium}=require('playwright');const APP='http://localhost:8099/index.html';const SB='https://mock.supabase.co';
let pass=0,fail=0;const ok=(c,m)=>{if(c){pass++;console.log('  ✓',m);}else{fail++;console.log('  ✗',m);}};
const reqs=[];let script=[];
(async()=>{
 const b=await chromium.launch();const ctx=await b.newContext({viewport:{width:390,height:844},serviceWorkers:'block'});const p=await ctx.newPage();const errs=[];
 p.on('pageerror',e=>errs.push(e.message));p.on('console',m=>{if(m.type()==='error'&&!/Failed to load resource/.test(m.text()))errs.push(m.text());});
 await p.route('**/app/config.js',r=>r.fulfill({contentType:'application/javascript',body:`export const CONFIG={supabaseUrl:'${SB}',supabaseKey:'k'};`}));
 await p.route(SB+'/**',route=>{const req=route.request();const path=new URL(req.url()).pathname;const json=(s,b)=>route.fulfill({status:s,contentType:'application/json',body:JSON.stringify(b)});
  if(path.startsWith('/auth/v1/token'))return json(200,{access_token:'a',refresh_token:'r',expires_in:3600,user:{id:'u',email:'a@x.com'}});
  if(path.startsWith('/rest/v1/plan_shares'))return json(200,[]);if(path.startsWith('/rest/v1/records'))return json(req.method()==='POST'?201:200,[]);
  if(path==='/functions/v1/coach'){reqs.push(req.postDataJSON());return json(200,script.length?script.shift():{content:[{type:'text',text:'?'}],stop_reason:'end_turn'});}
  return json(404,{});});
 await p.goto(APP);await p.waitForSelector('#view-auth:not(.hidden)');await p.fill('#authEmail','a@x.com');await p.fill('#authPass','password123');await p.click('#authSubmit');await p.waitForSelector('body[data-ready="1"]');
 await p.evaluate(async()=>{await idbPut('measurements',{id:'m1',date:todayStr(),weight:83},true);});await p.evaluate(()=>go('today'));await p.waitForTimeout(200);
 const wt=n=>p.waitForTimeout(n);
 console.log('A. Home has the describe box; nav says Home');
 ok(await p.$('#dtlInput')&&(await p.textContent('.nav [data-nav="today"]')).includes('Home'),'box + Home label');
 console.log('B. describe → parse → preview → edit → log');
 script=[{content:[{type:'tool_use',id:'f1',name:'parse_food',input:{meal:'breakfast',note:'assumed 2 slices',items:[{name:'Boiled eggs ×2',grams:100,kcal:155,protein:13,carbs:1,fat:11,confidence:'high'},{name:'Toast with butter',grams:70,kcal:230,protein:6,carbs:30,fat:9,confidence:'medium'},{name:'Flat white',grams:200,kcal:120,protein:6,carbs:9,fat:6,confidence:'low'}]}}],stop_reason:'tool_use'}];
 await p.fill('#dtlInput','2 eggs, toast with butter, flat white');await p.click('#dtlGo');await wt(500);
 const r=reqs[reqs.length-1];ok(r.kind==='food'&&r.tool_choice.name==='parse_food'&&r.messages[0].content==='2 eggs, toast with butter, flat white'&&/South Africa/.test(r.system[0].text),'forced parse_food request with the raw text');
 const pv=await p.textContent('#dtlOut');ok(/505 kcal/.test(pv)&&/Boiled eggs ×2/.test(pv)&&/assumed 2 slices/.test(pv)&&/rough/.test(pv),'preview: totals, items, note, low-confidence badge: '+pv.slice(0,60));
 ok(await p.$eval('#dtlMeal',s=>s.value==='breakfast'),'meal preselected from the parse');
 await p.click('[data-dtlrm="2"]');await wt(100);ok(/385 kcal/.test(await p.textContent('#dtlOut')),'removing a line recomputes totals');
 await p.fill('[data-dtlk="1"]','250');await p.check('[data-dtlsave="1"]');await p.selectOption('#dtlMeal','lunch');
 await p.click('#dtlLog');await wt(400);
 const log=await p.evaluate(()=>idbGetAll('log'));
 ok(log.length===2&&log.every(e=>e.meal==='lunch'&&e.estimated)&&log.find(e=>/Toast/.test(e.name)).kcal===250,'2 items logged to lunch, edited kcal kept, flagged estimated');
 const saved=await p.evaluate(()=>idbGetAll('foods').then(a=>a.find(f=>/Toast/.test(f.name))));
 ok(saved&&saved.custom&&saved.serving==='100 g'&&saved.kcal===357,'saved-as-food stored per 100 g (250 kcal / 70 g → 357)');
 ok(await p.$eval('#dtlInput',i=>i.value==='')&&!(await p.textContent('#dtlOut')).trim(),'box cleared after logging');
 ok((await p.textContent('#view-today')).includes('Toast'),'Today shows the entries');
 console.log('C. recipe: ingredients + cooked weight → per-100 g food, logged by grams');
 await p.evaluate(()=>go('food'));await wt(200);await p.click('#addRecipeBtn');await p.waitForSelector('#rcSave');
 await p.fill('#rcName','Beef curry');
 const chick=await p.evaluate(()=>idbGetAll('foods').then(a=>a.find(f=>/chicken breast/i.test(f.name)&&servingUnit(f.serving))?.name));
 ok(!!chick,'found a weight-based seed food: '+chick);
 await p.fill('#rcQ',chick);await p.fill('#rcG','500');await p.click('#rcAdd');await wt(100);
 const rice=await p.evaluate(()=>idbGetAll('foods').then(a=>a.find(f=>/rice/i.test(f.name)&&servingUnit(f.serving))?.name));
 await p.fill('#rcQ',rice);await p.fill('#rcG','300');await p.click('#rcAdd');await wt(100);
 ok((await p.textContent('#rcList')).includes('500 g'),'ingredients listed');
 await p.fill('#rcCooked','1600');await wt(100);
 ok(/per 100 g cooked/.test(await p.textContent('#rcTotals')),'per-100 g cooked preview');
 await p.click('#rcSave');await wt(400);
 const rec=await p.evaluate(()=>idbGetAll('foods').then(a=>a.find(f=>f.name==='Beef curry')));
 const exp=await p.evaluate(async()=>{const a=await idbGetAll('foods');const c=a.find(f=>/chicken breast/i.test(f.name)&&servingUnit(f.serving)),r=a.find(f=>/rice/i.test(f.name)&&servingUnit(f.serving));const pc=foodPer100(c),pr=foodPer100(r);return Math.round((pc.kcal*5+pr.kcal*3)/16);});
 ok(rec&&rec.kind==='recipe'&&rec.serving==='100 g'&&rec.ingredients.length===2&&rec.cookedG===1600&&rec.kcal===exp,'recipe saved per 100 g cooked ('+(rec&&rec.kcal)+' kcal expected '+exp+')');
 ok((await p.textContent('#view-food')).includes('Beef curry')&&await p.$('[data-editrecipe]'),'recipe listed under My foods with edit');
 await p.click(`[data-logfood="${rec.id}"]`,{force:true});await p.waitForSelector('#mServ');
 ok(await p.$eval('#mServ',i=>i.value==='100'),'log sheet asks for grams');
 await p.fill('#mServ','220');await p.click('#mSave');await wt(300);
 const e=await p.evaluate(()=>idbGetAll('log').then(a=>a.find(x=>x.name==='Beef curry')));
 ok(e&&Math.abs(e.kcal-Math.round(rec.kcal*2.2))<=2&&/220 g/.test(e.serving||'')||e&&Math.abs(e.servings-2.2)<0.01,'220 g of the recipe logged: '+JSON.stringify({kcal:e&&e.kcal,servings:e&&e.servings}));
 console.log('D. offline fallback');
 await ctx.setOffline(true);await p.evaluate(()=>go('today'));await wt(200);await p.fill('#dtlInput','banana');await p.click('#dtlGo');await wt(300);
 ok(await p.evaluate(()=>curView==='food'&&foodSeg==='library'&&document.querySelector('#foodSearch').value==='banana'),'offline → local library search with the text');
 await ctx.setOffline(false);
 ok(!errs.length,'no console errors '+JSON.stringify(errs));
 await b.close();console.log(`\n${pass} passed, ${fail} failed`);process.exit(fail?1:0);
})().catch(e=>{console.error(e);process.exit(1);});
