const {chromium}=require('playwright');const APP='http://localhost:8099/index.html';
let pass=0,fail=0;const ok=(c,m)=>{if(c){pass++;console.log('  ✓',m);}else{fail++;console.log('  ✗',m);}};
(async()=>{
 const b=await chromium.launch();const ctx=await b.newContext({viewport:{width:390,height:844},serviceWorkers:'block'});const p=await ctx.newPage();const errs=[];
 p.on('pageerror',e=>errs.push(e.message));p.on('console',m=>{if(m.type()==='error')errs.push(m.text());});
 await p.goto(APP);await p.waitForSelector('#view-auth:not(.hidden)');await p.click('#authSkip');await p.waitForSelector('body[data-ready="1"]');
 console.log('A. catalog integrity');
 const info=await p.evaluate(()=>{const M=new Set(['chest','lats','upper-back','front-delts','side-delts','rear-delts','biceps','triceps','forearms','quads','hamstrings','glutes','calves','core','full-body']);
  const EQ=new Set(['barbell','rack','bench','dumbbell','kettlebell','pull-up-bar','dip-station','pulley','band','machine','box','rope','rower','bike','ab-wheel','ez-bar','trap-bar','landmine','smith','sled','plate','med-ball','rings','trx','treadmill','foam-roller','stairs','none']);
  const ids=new Set(),dupIds=[],badM=[],badP=[],badE=[],noRegion=[];
  for(const c of EX_CATALOG){if(ids.has(c.id))dupIds.push(c.id);ids.add(c.id);
   for(const m of [...c.primary,...c.secondary])if(!M.has(m))badM.push(c.id+':'+m);
   if(!EX_PATTERNS.includes(c.pattern))badP.push(c.id+':'+c.pattern);
   for(const e of c.equipment)if(!EQ.has(e))badE.push(c.id+':'+e);
   if(!c.region||c.region==='other')noRegion.push(c.id);}
  const names=EX_CATALOG.map(c=>c.name.toLowerCase());const dupNames=names.filter((n,i)=>names.indexOf(n)!==i);
  return{n:EX_CATALOG.length,dupIds,badM,badP,badE,noRegion,dupNames,cues:EX_CATALOG.filter(c=>c.cues).length,stored:null};});
 ok(info.n>=270,'catalog size '+info.n);
 ok(!info.dupIds.length,'no duplicate ids '+JSON.stringify(info.dupIds));
 ok(!info.dupNames.length,'no duplicate names '+JSON.stringify(info.dupNames));
 ok(!info.badM.length,'muscle vocabulary valid '+JSON.stringify(info.badM.slice(0,5)));
 ok(!info.badP.length,'patterns valid '+JSON.stringify(info.badP.slice(0,5)));
 ok(!info.badE.length,'equipment tokens valid '+JSON.stringify(info.badE.slice(0,5)));
 ok(!info.noRegion.length,'every entry has a region '+JSON.stringify(info.noRegion.slice(0,5)));
 ok(info.cues>=180,'cues authored: '+info.cues);
 ok(await p.evaluate(()=>idbGetAll('exercises').then(a=>a.length===EX_CATALOG.length)),'exercises store holds the whole catalog');
 ok(await p.evaluate(()=>idbGet('kv','exerciseSeedVersion').then(v=>v.v===2)),'seed version 2');
 console.log('B. per-side in labels');
 ok(await p.evaluate(()=>PROG.days.A.ex.find(e=>e.name==='KB Goblet Reverse Lunge').target==='3 × 10 per leg'),'lunge label says per leg');
 ok(await p.evaluate(()=>PROG.days.C.ex.find(e=>e.name==='KB Single-leg RDL').target==='3 × 10–12 per leg'),'single-leg RDL says per leg');
 ok(await p.evaluate(()=>PROG.days.A.ex.find(e=>e.name==='Back Squat').target==='4 × 5'),'bilateral unchanged');
 ok(await p.evaluate(()=>sideWord('Concentration Curl')==='arm'&&sideWord('DB Row')==='arm'&&sideWord('Step-up')==='leg'&&sideWord('Side Plank')==='side'),'sideWord picks arm / leg / side');
 await p.evaluate(()=>go('train'));await p.click('#view-train [data-startday="A"]',{force:true});await p.waitForSelector('#view-session:not(.hidden) #woSave');
 const hdr=await p.textContent('#view-session [data-ex="4"]');
 ok(/3 × 10 per leg/.test(hdr)&&/REPS \/ LEG/.test(hdr),'logger header + column say per leg');
 await p.evaluate(()=>go('train'));
 console.log('C. library view');
 await p.click('#libBtn',{force:true});await p.waitForSelector('#libQ');
 ok(await p.evaluate(()=>curView==='library'&&!document.querySelector('#view-library').classList.contains('hidden')),'library view opens (full screen, not a modal)');
 const total=await p.$$eval('#libBody [data-libex]',r=>r.length);ok(total===info.n,'lists every exercise ('+total+')');
 await p.click('[data-libpat="lunge"]');ok(await p.$$eval('#libBody [data-libex]',r=>r.length>8&&r.length<40),'pattern filter narrows');
 await p.click('[data-libpat=""]');await p.fill('#libQ','curl');await p.waitForTimeout(100);
 const curls=await p.$$eval('#libBody [data-libex] .n',r=>r.map(x=>x.textContent));ok(curls.length>=8&&curls.every(n=>/curl/i.test(n)),'search "curl" → '+curls.length+' curls');
 ok(curls.some(n=>/Concentration Curl.*per arm/.test(n)),'unilateral rows show "per arm" in the list');
 await p.click('[data-libex="ez-curl"]',{force:true});await p.waitForTimeout(150);
 const det=await p.textContent('[data-libdetail="ez-curl"]');
 ok(/How:/.test(det)&&/Works:.*biceps/.test(det)&&/Kit:.*ez-bar ✗/.test(det),'detail shows cue, muscles and missing kit (no EZ bar in default gym)');
 ok(/Swap for:/.test(det)&&/DB Curl|Barbell Curl|KB Curl|Band Curl/.test(det),'equipment-aware alternatives offered');
 await p.click('[data-libgo="db-curl"]',{force:true});await p.waitForTimeout(150);
 ok(await p.evaluate(()=>libOpen==='db-curl'&&!document.querySelector('[data-libdetail="db-curl"]').classList.contains('hidden')),'tapping an alternative opens it');
 await p.fill('#libQ','');await p.click('#libMine');await p.waitForTimeout(100);
 const mine=await p.$$eval('#libBody [data-libex]',r=>r.length);ok(mine<total&&mine>150,'"only my gym" filter: '+mine+' of '+total);
 await p.click('#libBack');ok(await p.evaluate(()=>curView==='train'),'back to Train');await p.waitForTimeout(400);
 console.log('D. editor autocompletes + pre-ticks per side from catalog');
 await p.click('#view-train [data-editday="B"]',{force:true});await p.waitForSelector('#pdName');
 ok(await p.$eval('#exNames option',o=>!!o),'datalist of catalog names present');
 await p.fill('#pdName','Bulgarian Split Squat');await p.dispatchEvent('#pdName','change');
 ok(await p.$eval('#pdSide',c=>c.checked),'per side auto-ticked for a unilateral exercise');
 await p.fill('#pdSets','3');await p.fill('#pdMin','8');await p.click('#pdAdd');
 ok((await p.textContent('#pdList')).includes('3 × 8 per leg'),'added exercise labelled per leg');
 await p.evaluate(()=>go('train'));
 ok(!errs.length,'no console errors '+JSON.stringify(errs));
 await b.close();console.log(`\n${pass} passed, ${fail} failed`);process.exit(fail?1:0);
})().catch(e=>{console.error(e);process.exit(1);});
