const {chromium}=require('playwright');const APP='http://localhost:8099/index.html';
let pass=0,fail=0;const ok=(c,m)=>{if(c){pass++;console.log('  ✓',m);}else{fail++;console.log('  ✗',m);}};
(async()=>{
 const b=await chromium.launch();const ctx=await b.newContext({viewport:{width:390,height:844},serviceWorkers:'block'});const p=await ctx.newPage();const errs=[];
 p.on('pageerror',e=>errs.push(e.message));p.on('console',m=>{if(m.type()==='error')errs.push(m.text());});
 await p.goto(APP);await p.waitForSelector('#view-auth:not(.hidden)');await p.click('#authSkip');await p.waitForSelector('body[data-ready="1"]');
 console.log('A. parser + label round-trip');
 const cases=await p.evaluate(()=>[['4 × 5',null],['3 × 6–8',null],['3 × AMRAP',null],['8 × 40s',null],['3 rounds',null],['5 × 20',null],['3 x 10-12',null],['3 × 30','time'],['garbage',null]].map(([s,m])=>[s,parseTarget(s,m),targetLabel(parseTarget(s,m))]));
 const exp={'4 × 5':'4 × 5','3 × 6–8':'3 × 6–8','3 × AMRAP':'3 × AMRAP','8 × 40s':'8 × 40s','3 rounds':'3 rounds','5 × 20':'5 × 20','3 x 10-12':'3 × 10–12','3 × 30':'3 × 30s','garbage':''};
 for(const [s,t,l] of cases)ok(l===exp[s],`"${s}" → ${JSON.stringify(t)} → "${l}"`);
 console.log('B. seeded plan is structured');
 ok(await p.evaluate(()=>PROG.days.A.ex.every(e=>e.tgt&&e.target===exTargetText(e))),'every Day A exercise has tgt + derived label');
 ok(await p.evaluate(()=>{const c=PROG.days.C.ex.find(e=>/circuit/i.test(e.name));return c.mode==='rounds'&&c.items.length===3&&c.tgt.rounds===3;}),'Core circuit is a rounds circuit with 3 items');
 ok(await p.evaluate(()=>PROG.days.A.ex.find(e=>e.name==='KB Goblet Reverse Lunge').perSide===true),'per-side preserved');
 console.log('C. legacy free-text program normalises in memory');
 await p.evaluate(async()=>{const pl=await idbGet('plans','plan-default');pl.days.A.ex=[{name:'Back Squat',target:'5 × 5',type:'barbell-lower',rest:150},{name:'Skipping',target:'8 × 40s',type:'other',mode:'time',rest:20},{name:'Core circuit',target:'3 rounds',type:'other',rest:45}];await idbPut('plans',pl);});
 await p.reload();await p.waitForSelector('body[data-ready="1"]');
 ok(await p.evaluate(()=>{const e=PROG.days.A.ex;return e[0].tgt.sets===5&&e[0].tgt.reps.min===5&&e[1].tgt.secs===40&&e[1].mode==='time'&&e[2].mode==='rounds'&&e[2].items.length===3;}),'legacy strings → tgt / time / circuit items');
 ok(await p.evaluate(()=>idbGet('plans','plan-default').then(pl=>!pl.days.A.ex[0].tgt)),'migration did NOT write back to the store (LWW safety)');
 console.log('D. logger renders circuit rounds and saves them');
 await p.evaluate(()=>go('train'));await p.click('#view-train [data-startday="A"]',{force:true});await p.waitForSelector('#view-session:not(.hidden) #woSave');
 ok(await p.$$eval('#view-session [data-ex="2"] .sets .setrow.rounds',r=>r.length===3),'3 round rows for the circuit');
 ok((await p.textContent('#view-session [data-ex="2"]')).includes('Each round: Plank 40 s · Dead Bug 10/side · Hanging Knee Raise 10'),'circuit items shown in the header');
 await p.click('#view-session [data-ex="2"] .sets .setrow:nth-child(1) [data-tickset]',{force:true});
 await p.fill('#view-session [data-ex="0"] .setrow input[aria-label="Set 1 weight, kg"]','100');await p.fill('#view-session [data-ex="0"] .setrow input[aria-label^="Set 1 reps"]','5');
 await p.click('#woSave',{force:true});await p.waitForTimeout(300);
 const w=await p.evaluate(()=>idbGetAll('workouts').then(a=>a[0]));
 ok(w&&w.exercises[2].mode==='rounds'&&w.exercises[2].sets[0].done===true&&w.exercises[2].items.length===3,'saved session keeps rounds mode, done tick and items');
 ok(w.exercises[0].tgt&&w.exercises[0].tgt.sets===5,'saved session carries structured tgt');
 await p.waitForTimeout(200);ok((await p.textContent('#workoutHistory')).includes('4 sets'),'history counts the ticked round (3 items) + the squat set ('+(await p.textContent('#workoutHistory')).match(/\d+ sets/)+')');
 console.log('E. editor builds structured targets');
 await p.click('#view-train [data-editday="A"]',{force:true});await p.waitForSelector('#pdSets');
 await p.fill('#pdName','Bench Press');await p.fill('#pdSets','3');await p.fill('#pdMin','6');await p.fill('#pdMax','8');await p.click('#pdAdd');
 await p.selectOption('#pdMode','rounds');ok(await p.$eval('#pdItems',t=>!t.classList.contains('hidden')),'circuit textarea appears for rounds mode');
 await p.fill('#pdName','Finisher');await p.fill('#pdSets','2');await p.fill('#pdItems','Plank 30s\nDead bug 8 per side\nBurpees 10');await p.click('#pdAdd');
 await p.selectOption('#pdMode','reps');await p.fill('#pdName','Chin-ups');await p.fill('#pdSets','3');await p.check('#pdAmrap');await p.click('#pdAdd');
 await p.click('#pdSave');await p.waitForTimeout(300);
 const ex=await p.evaluate(()=>idbGet('plans','plan-default').then(pl=>pl.days.A.ex));
 ok(ex.some(e=>e.name==='Bench Press'&&e.target==='3 × 6–8'&&e.tgt.reps.max===8),'reps target built: '+ex.find(e=>e.name==='Bench Press')?.target);
 const fin=ex.find(e=>e.name==='Finisher');
 ok(fin&&fin.mode==='rounds'&&fin.tgt.rounds===2&&fin.items.length===3&&fin.items[1].perSide===true&&fin.items[0].secs===30&&fin.items[2].reps===10,'circuit built from lines: '+JSON.stringify(fin&&fin.items));
 ok(ex.some(e=>e.name==='Chin-ups'&&e.target==='3 × AMRAP'),'AMRAP target built');
 ok(!errs.length,'no console errors '+JSON.stringify(errs));
 await b.close();console.log(`\n${pass} passed, ${fail} failed`);process.exit(fail?1:0);
})().catch(e=>{console.error(e);process.exit(1);});
