const {chromium}=require('playwright');const APP='http://localhost:8099/index.html';
let pass=0,fail=0;const ok=(c,m)=>{if(c){pass++;console.log('  ✓',m);}else{fail++;console.log('  ✗',m);}};
(async()=>{
 const b=await chromium.launch();const ctx=await b.newContext({viewport:{width:390,height:844},serviceWorkers:'block'});const p=await ctx.newPage();const errs=[];
 p.on('pageerror',e=>errs.push(e.message));p.on('console',m=>{if(m.type()==='error')errs.push(m.text());});
 await p.addInitScript(()=>{window.__wl=[];Object.defineProperty(navigator,'wakeLock',{configurable:true,value:{request:async t=>{window.__wl.push('req');return{release:async()=>{window.__wl.push('rel');},addEventListener(){}};}}});});
 await p.goto(APP);await p.waitForSelector('#view-auth:not(.hidden)');await p.click('#authSkip');await p.waitForSelector('body[data-ready="1"]');
 const wt=n=>p.waitForTimeout(n);
 console.log('A. analytics primitives');
 ok(await p.evaluate(()=>epley(100,5)===117&&epley(0,10)===0),'epley');
 ok(await p.evaluate(()=>exIdOf('Squat')==='back-squat'&&exIdOf('barbell squat')==='back-squat'&&exIdOf('Weird Thing')==='name:weird thing'),'exIdOf resolves aliases, falls back to name');
 console.log('B. session is a full-screen view');
 await p.evaluate(()=>go('train'));await wt(200);
 ok((await p.textContent('#dayBtns')).includes('Active plan'),'train shows plan row');
 ok(await p.$('#trainWeek .card'),'week card rendered');
 await p.click('#view-train [data-startday="A"]',{force:true});await p.waitForSelector('#view-session:not(.hidden) #woSave');
 ok(await p.evaluate(()=>curView==='session'&&document.body.classList.contains('session-mode')&&getComputedStyle(document.querySelector('.nav')).display==='none'),'session view open, nav hidden');
 ok(await p.evaluate(()=>!document.querySelector('#modalRoot').children.length),'no modal used');
 ok(await p.evaluate(()=>window.__wl.includes('req')),'wake lock requested');
 ok(await p.$eval('#view-session [data-ex="0"] .exhead .en',e=>e.textContent.includes('Back Squat')),'exercise header is a link to history');
 await p.fill('#view-session [data-ex="0"] .setrow input[aria-label="Set 1 weight, kg"]','60');await p.fill('#view-session [data-ex="0"] .setrow input[aria-label^="Set 1 reps"]','5');
 await p.fill('#view-session [data-ex="0"] .setrow input[aria-label="Set 2 weight, kg"]','60');await p.fill('#view-session [data-ex="0"] .setrow input[aria-label^="Set 2 reps"]','5');
 ok(await p.$eval('#view-session [data-ex="0"] .setrow:nth-child(1)',r=>!r.classList.contains('pr')),'no PB on the very first session (nothing to beat)');
 await p.click('#sesBack');await wt(600);
 ok(await p.evaluate(()=>curView==='train'&&!document.body.classList.contains('session-mode')),'back returns to Train, nav restored');
 ok(await p.evaluate(()=>window.__wl.includes('rel')),'wake lock released on leave');
 ok((await p.textContent('#dayBtns')).includes('Resume'),'draft offered for resume');
 await p.click('#view-train [data-startday="A"]',{force:true});await p.waitForSelector('#view-session:not(.hidden) #woSave');
 ok(await p.$eval('#view-session [data-ex="0"] .setrow input[aria-label="Set 1 weight, kg"]',i=>i.value==='60'),'draft resumed with values');
 await p.click('#woSave',{force:true});await wt(500);
 ok(await p.evaluate(()=>idbGetAll('workouts').then(a=>a.length===1&&Array.isArray(a[0].prs)&&a[0].prs.length===0)),'first session saved, no PRs');
 console.log('C. second session: last/best shown, PB detected live and stored');
 await p.evaluate(async()=>{const w=(await idbGetAll('workouts'))[0];w.date='2026-08-11';await idbPut('workouts',w);});
 await p.evaluate(()=>go('train'));await wt(200);
 await p.click('#view-train [data-startday="A"]',{force:true});await p.waitForSelector('#view-session:not(.hidden) #woSave');
 const hint=await p.textContent('#view-session [data-ex="0"] .lasthint');
 ok(/Last: 60×5, 60×5/.test(hint)&&/Best: 60 × 5/.test(hint)&&/e1RM 70 kg/.test(hint),'Last + Best + e1RM line: '+hint.trim());
 await p.fill('#view-session [data-ex="0"] .setrow input[aria-label="Set 1 weight, kg"]','65');await p.fill('#view-session [data-ex="0"] .setrow input[aria-label^="Set 1 reps"]','5');
 ok(await p.$eval('#view-session [data-ex="0"] .setrow:nth-child(1)',r=>r.classList.contains('pr')&&r.classList.contains('beat')),'65×5 flagged PB + beat');
 ok(/PB — heaviest ever: 65 kg × 5/.test(await p.textContent('#view-session [data-prline="0"]')),'PB line text');
 await p.fill('#view-session [data-ex="0"] .setrow input[aria-label="Set 1 weight, kg"]','60');
 ok(await p.$eval('#view-session [data-ex="0"] .setrow:nth-child(1)',r=>!r.classList.contains('pr')),'PB flag removed when the value drops');
 await p.fill('#view-session [data-ex="0"] .setrow input[aria-label^="Set 1 reps"]','7');
 ok(await p.$eval('#view-session [data-ex="0"] .setrow:nth-child(1)',r=>r.classList.contains('pr')),'60×7 = rep PB at that weight');
 await p.click('#sesFinish');await wt(600);
 const w2=await p.evaluate(()=>idbGetAll('workouts').then(a=>a.sort((x,y)=>x.date<y.date?1:-1)[0]));
 ok(w2.prs&&w2.prs.length===1&&w2.prs[0].name==='Back Squat'&&/most reps at 60 kg: 7/.test(w2.prs[0].text),'PR stored on the session: '+JSON.stringify(w2.prs));
 await wt(300);
 ok((await p.textContent('#workoutHistory')).includes('1 PB'),'history card shows PB badge');
 ok((await p.textContent('#trainWeek')).includes('1 of 3 session'),'week card: 1 of 3 sessions');
 ok((await p.textContent('#trainWeek')).includes('Lower'),'week card: region bars');
 await p.click('#trainWeek details summary');ok((await p.textContent('#trainWeek table')).includes('quads'),'by-muscle table shows quads');
 console.log('D. exercise history screen');
 await p.click('#view-train [data-openwo]',{force:true});await p.waitForSelector('#view-session:not(.hidden)');
 await p.click('#view-session [data-exhist="Back Squat"]',{force:true});await wt(400);
 ok(await p.evaluate(()=>curView==='exhist'),'exhist view opens from the logger');
 const eh=await p.textContent('#exhBody');
 ok(/heaviest set/.test(eh)&&/est\. 1RM/.test(eh),'kpis rendered');
 ok(await p.$('#exhChart'),'chart drawn with 2 sessions');
 ok(await p.$$eval('#exhBody [data-openwo]',r=>r.length===2),'two sessions listed');
 await p.click('#exhBack');await wt(200);
 ok(await p.evaluate(()=>curView==='session'),'back returns to the session');
 await p.click('#sesBack');await wt(200);
 console.log('E. flat visual rules');
 const flat=await p.evaluate(()=>{const cs=el=>getComputedStyle(el);return{hdr:cs(document.querySelector('.app-header')).backdropFilter,card:cs(document.querySelector('.card')).boxShadow,btn:cs(document.querySelector('.btn')).boxShadow,nav:cs(document.querySelector('.nav')).backdropFilter};});
 ok((flat.hdr==='none'||!flat.hdr)&&(flat.nav==='none'||!flat.nav),'no backdrop blur on header/nav');
 ok(flat.card==='none'&&flat.btn==='none','no box-shadow on cards/buttons: '+JSON.stringify(flat));
 ok(!errs.length,'no console errors '+JSON.stringify(errs));
 await b.close();console.log(`\n${pass} passed, ${fail} failed`);process.exit(fail?1:0);
})().catch(e=>{console.error(e);process.exit(1);});
