/* ---------- Exercise library extension (v3 stage 2) ----------
   Adds ~190 entries to the base catalog in seed.js, same terse format:
   [id, name, pattern, primary, secondary, equipment, opts?]
   opts: {u:1 unilateral · t:1 timed · rest:n · load:'bw'|'bw+'|'band'|'none' · alias:'a,b' · c:'one-line cue'}
   Patterns: squat hinge lunge horizontal-push vertical-push horizontal-pull vertical-pull
             carry core isolation conditioning mobility
   Muscles:  chest lats upper-back front-delts side-delts rear-delts biceps triceps forearms
             quads hamstrings glutes calves core full-body
   Equipment vocabulary (matches My gym): barbell rack bench dumbbell kettlebell pull-up-bar
             dip-station pulley band machine box rope rower bike ab-wheel ez-bar trap-bar
             landmine smith sled plate med-ball rings trx treadmill foam-roller none */
const EX_SEED_MORE=[
 // ---- squat variations ----
 ['zercher-squat','Zercher Squat','squat','quads,glutes','core,upper-back','barbell,rack',{c:'Bar in the crook of the elbows; stay tall, knees out.'}],
 ['safety-bar-squat','Safety-bar Squat','squat','quads,glutes','upper-back','barbell,rack',{c:'Upright torso; drive the handles up out of the hole.'}],
 ['pause-squat','Paused Back Squat','squat','quads,glutes','hamstrings,core','barbell,rack',{c:'2-second dead stop at the bottom, no bounce.'}],
 ['tempo-squat','Tempo Squat (3-1-1)','squat','quads,glutes','hamstrings','barbell,rack',{c:'3 s down, 1 s pause, drive up — own every inch.'}],
 ['overhead-squat','Overhead Squat','squat','quads,glutes','core,front-delts','barbell',{rest:120,c:'Bar over mid-foot; push up into the bar the whole way.'}],
 ['db-goblet-squat','DB Goblet Squat','squat','quads,glutes','core','dumbbell',{rest:90,c:'Hug the bell to your chest; elbows inside the knees at the bottom.'}],
 ['kb-front-squat','KB Front Squat (rack)','squat','quads,glutes','core','kettlebell',{rest:90,c:'Bells racked on the forearms; sit between the heels.'}],
 ['db-squat','DB Squat','squat','quads,glutes','core','dumbbell',{rest:90,c:'Dumbbells at the sides; chest up, full depth.'}],
 ['landmine-squat','Landmine Squat','squat','quads,glutes','core','landmine',{rest:90,c:'Hold the sleeve at the chest; the arc guides you upright.'}],
 ['smith-squat','Smith Machine Squat','squat','quads,glutes','hamstrings','smith',{rest:90,c:'Feet slightly forward of the bar; control the descent.'}],
 ['wall-sit','Wall Sit','squat','quads','glutes','none',{t:1,load:'bw',rest:45,c:'Thighs parallel, back flat on the wall, breathe.'}],
 ['jump-squat','Jump Squat','conditioning','quads,glutes','calves','none',{load:'bw',rest:60,c:'Land soft, reset, jump again — quality over speed.'}],
 ['sissy-squat','Sissy Squat','isolation','quads','','none',{load:'bw+',rest:60,c:'Knees travel forward, hips open; hold something for balance.'}],
 ['belt-squat','Belt Squat','squat','quads,glutes','hamstrings','machine',{rest:90,c:'Load through the hips — great when the back needs a rest.'}],
 // ---- hinge variations ----
 ['deficit-dl','Deficit Deadlift','hinge','hamstrings,glutes','upper-back,core','barbell,plate',{c:'Stand on a plate; longer pull, patient off the floor.'}],
 ['rack-pull','Rack Pull','hinge','upper-back,glutes','hamstrings,forearms','barbell,rack',{c:'Pins at knee height; lock out hard, no leaning back.'}],
 ['db-rdl','DB Romanian Deadlift','hinge','hamstrings,glutes','upper-back','dumbbell',{rest:90,c:'Push the hips back; dumbbells slide down the thighs.'}],
 ['kb-rdl','KB Romanian Deadlift','hinge','hamstrings,glutes','core','kettlebell',{rest:90,c:'Soft knees, flat back, feel the hamstrings load.'}],
 ['kb-deadlift','KB Deadlift','hinge','glutes,hamstrings','quads,core','kettlebell',{rest:90,c:'Bell between the feet; stand up by driving the floor away.'}],
 ['sl-db-rdl','Single-leg DB RDL','hinge','hamstrings,glutes','core','dumbbell',{u:1,rest:75,c:'Hips square, back leg reaches straight behind you.'}],
 ['bb-hip-thrust','Barbell Hip Thrust','hinge','glutes','hamstrings','barbell,bench',{rest:90,c:'Chin tucked, ribs down; squeeze hard at the top.'}],
 ['glute-bridge','Glute Bridge','hinge','glutes','hamstrings,core','none',{load:'bw+',rest:45,c:'Drive through the heels; pause at the top.'}],
 ['sl-glute-bridge','Single-leg Glute Bridge','hinge','glutes','hamstrings,core','none',{u:1,load:'bw',rest:45,c:'Keep the hips level; don’t let the free side drop.'}],
 ['kb-swing-single','Single-arm KB Swing','conditioning','glutes,hamstrings','core,forearms','kettlebell',{u:1,rest:60,c:'Same hinge as the two-hand swing; shoulder packed, no twist.'}],
 ['nordic-curl','Nordic Hamstring Curl','isolation','hamstrings','glutes','none',{load:'bw',rest:90,c:'Lower as slowly as you can; push back up if needed.'}],
 ['leg-curl','Leg Curl','isolation','hamstrings','calves','machine',{rest:60,c:'Control the way back; don’t let the weight yank you.'}],
 ['reverse-hyper','Reverse Hyperextension','hinge','glutes,hamstrings','core','machine',{rest:60,c:'Legs swing up from the hips; no lower-back arching.'}],
 ['cable-pull-through','Cable Pull-through','hinge','glutes,hamstrings','core','pulley',{rest:60,c:'Face away, hinge back, snap the hips through.'}],
 ['band-good-morning','Band Good Morning','hinge','hamstrings','glutes','band',{load:'band',rest:45,c:'Band over the neck, under the feet; hinge until you feel the hamstrings.'}],
 // ---- lunge / single leg ----
 ['db-split-squat','DB Split Squat','lunge','quads,glutes','hamstrings','dumbbell',{u:1,c:'Long stance, back knee straight down; front foot flat.'}],
 ['bb-split-squat','Barbell Bulgarian Split Squat','lunge','quads,glutes','hamstrings','barbell,rack,bench',{u:1,c:'Torso slightly forward for glutes, upright for quads.'}],
 ['lateral-lunge','Lateral Lunge','lunge','quads,glutes','hamstrings','dumbbell',{u:1,rest:60,c:'Step wide, sit into one hip, keep the other leg straight.'}],
 ['curtsy-lunge','Curtsy Lunge','lunge','glutes,quads','hamstrings','dumbbell',{u:1,rest:60,c:'Cross behind; keep the front knee tracking over the toes.'}],
 ['kb-front-rack-lunge','KB Front-rack Reverse Lunge','lunge','quads,glutes','core','kettlebell',{u:1,c:'Bells racked; brace hard so the torso stays tall.'}],
 ['bb-reverse-lunge','Barbell Reverse Lunge','lunge','quads,glutes','hamstrings','barbell,rack',{u:1,c:'Step back, drop the knee, drive through the front heel.'}],
 ['box-step-up','High Box Step-up','lunge','glutes,quads','hamstrings','box',{u:1,load:'bw+',c:'Box at knee height or above; no push off the back leg.'}],
 ['skater-squat','Skater Squat','lunge','quads,glutes','core','none',{u:1,load:'bw+',rest:60,c:'Back knee reaches to a pad behind you; torso leans forward.'}],
 ['shrimp-squat','Shrimp Squat','lunge','quads,glutes','core','none',{u:1,load:'bw',rest:60,c:'Hold the back foot; lower until the knee touches.'}],
 // ---- horizontal push ----
 ['pause-bench','Paused Bench Press','horizontal-push','chest','triceps,front-delts','barbell,bench',{c:'1 s dead pause on the chest, then drive.'}],
 ['decline-bench','Decline Bench Press','horizontal-push','chest','triceps','barbell,bench',{c:'Bar to the lower chest; keep the shoulders pinned.'}],
 ['spoto-press','Spoto Press','horizontal-push','chest','triceps','barbell,bench',{c:'Pause an inch above the chest — no touch.'}],
 ['db-floor-press','DB Floor Press','horizontal-push','chest,triceps','front-delts','dumbbell',{rest:90,c:'Elbows touch the floor each rep; press up and slightly in.'}],
 ['db-decline','Decline DB Press','horizontal-push','chest','triceps','dumbbell,bench',{c:'Lower to the sternum; press to a point over the shoulders.'}],
 ['neutral-db-bench','Neutral-grip DB Press','horizontal-push','chest,triceps','front-delts','dumbbell,bench',{c:'Palms facing; friendlier on the shoulders.'}],
 ['kb-floor-press','KB Floor Press','horizontal-push','chest,triceps','front-delts','kettlebell',{u:1,rest:75,c:'Bell rests on the forearm; press straight up.'}],
 ['landmine-press','Landmine Press','horizontal-push','chest,front-delts','triceps,core','landmine',{u:1,rest:75,c:'Press up and forward along the bar’s arc.'}],
 ['machine-chest-press','Machine Chest Press','horizontal-push','chest','triceps,front-delts','machine',{rest:75,c:'Handles at mid-chest; don’t lock the elbows out hard.'}],
 ['smith-bench','Smith Machine Bench','horizontal-push','chest','triceps','smith,bench',{c:'Set the bench so the bar meets the lower chest.'}],
 ['incline-pushup','Incline Push-up','horizontal-push','chest','triceps,core','box',{load:'bw',rest:45,c:'Hands on a box or bench; the higher, the easier.'}],
 ['decline-pushup','Decline Push-up','horizontal-push','chest,front-delts','triceps,core','box',{load:'bw+',rest:60,c:'Feet up on a box; hands under the shoulders.'}],
 ['diamond-pushup','Diamond Push-up','horizontal-push','triceps,chest','core','none',{load:'bw+',rest:60,c:'Hands together under the chest; elbows tucked.'}],
 ['archer-pushup','Archer Push-up','horizontal-push','chest,triceps','core','none',{u:1,load:'bw',rest:60,c:'Wide hands; bend one arm, keep the other straight.'}],
 ['ring-pushup','Ring Push-up','horizontal-push','chest','triceps,core','rings',{load:'bw+',rest:60,c:'Turn the rings out at the top; stay hollow.'}],
 ['band-pushup','Band-resisted Push-up','horizontal-push','chest','triceps','band',{load:'band',rest:60,c:'Band across the back, ends under the hands.'}],
 ['bb-bench-cg-pause','Close-grip Paused Bench','horizontal-push','triceps','chest','barbell,bench',{rest:90,c:'Index fingers on the smooth; pause, then press.'}],
 ['pec-deck','Pec Deck','isolation','chest','front-delts','machine',{rest:60,c:'Slight elbow bend; squeeze the pads together.'}],
 ['band-fly','Band Chest Fly','isolation','chest','front-delts','band',{load:'band',rest:45,c:'Anchor behind you; hug a barrel.'}],
 ['plate-squeeze-press','Plate Squeeze Press','isolation','chest','triceps','plate',{rest:60,c:'Squeeze the plates together the whole time.'}],
 // ---- vertical push ----
 ['seated-db-ohp','Seated DB Shoulder Press','vertical-push','front-delts','triceps,side-delts','dumbbell,bench',{c:'Back on the pad; press until the arms just lock.'}],
 ['arnold-press','Arnold Press','vertical-push','front-delts,side-delts','triceps','dumbbell',{c:'Start palms in, rotate out as you press.'}],
 ['z-press','Z Press','vertical-push','front-delts','core,triceps','barbell',{rest:90,c:'Seated on the floor, legs straight — no cheating with the legs.'}],
 ['kb-double-press','Double KB Press','vertical-push','front-delts','triceps,core','kettlebell',{rest:90,c:'Both bells racked; press together, lock out overhead.'}],
 ['kb-bottoms-up','Bottoms-up KB Press','vertical-push','front-delts','forearms,core','kettlebell',{u:1,rest:75,c:'Bell upside down; crush the handle.'}],
 ['landmine-viking','Viking / Landmine Shoulder Press','vertical-push','front-delts','triceps,core','landmine',{rest:90,c:'Both hands on the sleeve; press up and forward.'}],
 ['smith-ohp','Smith Machine Shoulder Press','vertical-push','front-delts','triceps','smith,bench',{c:'Bar just in front of the face; press to lockout.'}],
 ['machine-shoulder-press','Machine Shoulder Press','vertical-push','front-delts','triceps','machine',{rest:75,c:'Handles at ear height; press up, control down.'}],
 ['band-ohp','Band Overhead Press','vertical-push','front-delts','triceps','band',{load:'band',rest:60,c:'Stand on the band; press until the arms lock.'}],
 ['wall-hspu','Wall Handstand Push-up','vertical-push','front-delts','triceps,core','none',{load:'bw',rest:120,c:'Kick up to the wall; head to a pad and press.'}],
 // ---- vertical pull ----
 ['neutral-pullup','Neutral-grip Pull-up','vertical-pull','lats','biceps,upper-back','pull-up-bar',{load:'bw+',rest:90,c:'Palms facing; pull the chest to the hands.'}],
 ['wide-pullup','Wide-grip Pull-up','vertical-pull','lats','upper-back','pull-up-bar',{load:'bw+',rest:90,c:'Hands wide; drive the elbows down and back.'}],
 ['towel-pullup','Towel Pull-up','vertical-pull','lats,forearms','biceps','pull-up-bar',{load:'bw',rest:90,c:'Grip towels over the bar; grip goes first.'}],
 ['negative-pullup','Negative Pull-up','vertical-pull','lats','biceps,upper-back','pull-up-bar',{load:'bw',rest:90,c:'Jump to the top, lower over 3–5 s.'}],
 ['scap-pullup','Scapular Pull-up','vertical-pull','lats,upper-back','','pull-up-bar',{load:'bw',rest:45,c:'Arms straight; pull the shoulder blades down and together.'}],
 ['band-pulldown','Band Lat Pulldown','vertical-pull','lats','biceps','band',{load:'band',rest:60,c:'Anchor high; pull the elbows to the ribs.'}],
 ['close-grip-pulldown','Close-grip Pulldown','vertical-pull','lats','biceps','pulley',{rest:75,c:'V-handle; lean back a touch, pull to the upper chest.'}],
 ['ring-pullup','Ring Pull-up','vertical-pull','lats','biceps,upper-back','rings',{load:'bw+',rest:90,c:'Rotate to neutral at the top; full hang at the bottom.'}],
 ['muscle-up','Muscle-up','vertical-pull','lats,chest','triceps,core','pull-up-bar',{load:'bw',rest:120,c:'Explosive pull, fast transition, press out.'}],
 // ---- horizontal pull ----
 ['chest-supported-row','Chest-supported DB Row','horizontal-pull','upper-back,lats','biceps,rear-delts','dumbbell,bench',{rest:75,c:'Chest on an incline bench; row to the hips.'}],
 ['t-bar-row','T-bar / Landmine Row','horizontal-pull','upper-back,lats','biceps','landmine',{rest:90,c:'Hinge to ~45°; drive the elbows back.'}],
 ['meadows-row','Meadows Row','horizontal-pull','lats,upper-back','biceps','landmine',{u:1,rest:75,c:'Stand beside the sleeve; row to the hip.'}],
 ['seal-row','Seal Row','horizontal-pull','upper-back','lats,biceps','barbell,bench',{rest:75,c:'Lying flat on a raised bench — zero body English.'}],
 ['yates-row','Underhand Barbell Row','horizontal-pull','lats,upper-back','biceps','barbell',{rest:90,c:'Supinated grip, more upright; pull to the belly.'}],
 ['kb-gorilla-row','KB Gorilla Row','horizontal-pull','lats,upper-back','biceps,core','kettlebell',{u:1,rest:75,c:'Two bells on the floor; row one while the other anchors.'}],
 ['renegade-row','Renegade Row','horizontal-pull','lats,core','upper-back,biceps','dumbbell',{u:1,rest:60,c:'Plank on the bells; row without rotating the hips.'}],
 ['band-row','Band Row','horizontal-pull','upper-back','lats,biceps','band',{load:'band',rest:60,c:'Anchor at chest height; squeeze the blades.'}],
 ['trx-row','TRX / Ring Row','horizontal-pull','upper-back','lats,biceps','trx',{load:'bw+',rest:60,c:'Body straight; walk the feet forward to make it harder.'}],
 ['machine-row','Machine Row','horizontal-pull','upper-back','lats,biceps','machine',{rest:75,c:'Chest on the pad; pull the elbows past the ribs.'}],
 ['high-cable-row','High-pulley Row (to face)','horizontal-pull','upper-back,rear-delts','biceps','pulley',{rest:60,c:'Pull to the face with the elbows high.'}],
 ['single-arm-cable-row','Single-arm Cable Row','horizontal-pull','lats','biceps,upper-back','pulley',{u:1,rest:60,c:'Let the shoulder reach forward, then drive it back.'}],
 ['high-pulley-lat-row','High-to-low Pulley Row','horizontal-pull','lats,upper-back','biceps','pulley',{rest:75,c:'Kneel or sit; pull the handle from high to the hips.'}],
 // ---- shoulders ----
 ['cable-lat-raise','Cable Lateral Raise','isolation','side-delts','','pulley',{u:1,rest:45,c:'Cable behind the body; lead with the elbow.'}],
 ['band-lat-raise','Band Lateral Raise','isolation','side-delts','','band',{load:'band',rest:45,c:'Stand on the band; raise to shoulder height.'}],
 ['upright-row','Upright Row','isolation','side-delts,upper-back','biceps','ez-bar',{rest:60,c:'Wide grip, elbows lead; stop at chest height.'}],
 ['db-rear-fly-incline','Incline Rear-delt Fly','isolation','rear-delts','upper-back','dumbbell,bench',{rest:45,c:'Chest on the bench; sweep the arms out and back.'}],
 ['band-pull-apart','Band Pull-apart','isolation','rear-delts,upper-back','','band',{load:'band',rest:30,c:'Arms straight; pull the band to the chest.'}],
 ['cable-face-pull','Cable Face Pull','isolation','rear-delts','upper-back','pulley',{rest:60,c:'Rope to the forehead; thumbs back, elbows high.'}],
 ['plate-front-raise','Plate Front Raise','isolation','front-delts','core','plate',{rest:45,c:'Raise to eye level; no swinging.'}],
 ['kb-halo','KB Halo','mobility','front-delts,upper-back','core','kettlebell',{rest:30,c:'Circle the bell tightly around the head; ribs down.'}],
 ['db-shrug','DB Shrug','isolation','upper-back','forearms','dumbbell',{rest:60,c:'Straight up to the ears; hold a second.'}],
 ['trap-bar-shrug','Trap-bar Shrug','isolation','upper-back','forearms','trap-bar',{rest:60,c:'Neutral grip; shrug and pause.'}],
 ['y-raise','Prone Y Raise','isolation','rear-delts,upper-back','','dumbbell,bench',{rest:45,c:'Thumbs up, arms in a Y; tiny weights.'}],
 // ---- arms ----
 ['ez-curl','EZ-bar Curl','isolation','biceps','forearms','ez-bar',{c:'Elbows pinned to the sides; full stretch at the bottom.'}],
 ['incline-curl','Incline DB Curl','isolation','biceps','','dumbbell,bench',{c:'Arms hang behind you; long stretch, no swing.'}],
 ['concentration-curl','Concentration Curl','isolation','biceps','','dumbbell',{u:1,c:'Elbow braced on the thigh; squeeze at the top.'}],
 ['cable-curl','Cable Curl','isolation','biceps','forearms','pulley',{c:'Constant tension; don’t let the stack touch down.'}],
 ['band-curl','Band Curl','isolation','biceps','forearms','band',{load:'band',rest:45,c:'Stand on the band; hardest at the top — hold it.'}],
 ['kb-curl','KB Curl','isolation','biceps','forearms','kettlebell',{c:'Hold the horns; curl without leaning back.'}],
 ['zottman-curl','Zottman Curl','isolation','biceps,forearms','','dumbbell',{c:'Curl palms up, rotate, lower palms down.'}],
 ['reverse-curl','Reverse Curl','isolation','forearms,biceps','','ez-bar',{c:'Palms down; wrists straight.'}],
 ['spider-curl','Spider Curl','isolation','biceps','','dumbbell,bench',{c:'Chest on an incline bench; arms hang straight down.'}],
 ['chinup-curl','Bodyweight Chin-up Curl','isolation','biceps','lats','pull-up-bar',{load:'bw',rest:60,c:'Narrow underhand grip; think “curl yourself up”.'}],
 ['wrist-curl','Wrist Curl','isolation','forearms','','dumbbell',{rest:45,c:'Forearms on the thighs; roll the wrists up.'}],
 ['dead-hang','Dead Hang','carry','forearms','lats,core','pull-up-bar',{t:1,load:'bw',rest:60,c:'Relaxed shoulders or active — either way, just hang.'}],
 ['bench-dip','Bench Dip','isolation','triceps','chest','bench',{load:'bw+',rest:60,c:'Hands behind you on the bench; elbows straight back.'}],
 ['db-kickback','Triceps Kickback','isolation','triceps','','dumbbell',{u:1,rest:45,c:'Upper arm parallel to the floor; extend and squeeze.'}],
 ['rope-pushdown','Rope Pushdown','isolation','triceps','','pulley',{rest:60,c:'Split the rope at the bottom; elbows still.'}],
 ['oh-cable-ext','Overhead Cable Extension','isolation','triceps','','pulley',{rest:60,c:'Face away from the pulley; extend from behind the head.'}],
 ['band-pushdown','Band Pushdown','isolation','triceps','','band',{load:'band',rest:45,c:'Anchor high; elbows glued to the ribs.'}],
 ['ez-skullcrusher','EZ-bar Skullcrusher','isolation','triceps','','ez-bar,bench',{c:'Lower to the forehead or behind the head; elbows in.'}],
 ['db-skullcrusher','DB Skullcrusher','isolation','triceps','','dumbbell,bench',{c:'Palms facing; lower beside the ears.'}],
 ['jm-press','JM Press','isolation','triceps','chest','barbell,bench',{rest:75,c:'Half bench, half skullcrusher — bar to the chin.'}],
 ['tate-press','Tate Press','isolation','triceps','','dumbbell,bench',{c:'Elbows flare out; dumbbells touch the chest.'}],
 ['ring-dip','Ring Dip','horizontal-push','triceps,chest','front-delts','rings',{load:'bw+',rest:90,c:'Turn the rings out at lockout; shoulders down.'}],
 // ---- legs: isolation & accessories ----
 ['leg-ext','Leg Extension','isolation','quads','','machine',{rest:60,c:'Squeeze at the top; lower under control.'}],
 ['reverse-nordic','Reverse Nordic','isolation','quads','core','none',{load:'bw',rest:60,c:'Kneel tall, lean back with straight hips.'}],
 ['spanish-squat','Spanish Squat','isolation','quads','glutes','band',{load:'band',rest:60,c:'Band behind the knees anchored in front; sit back.'}],
 ['seated-calf','Seated Calf Raise','isolation','calves','','machine',{rest:45,c:'Full stretch at the bottom, pause at the top.'}],
 ['standing-calf','Standing Calf Raise (loaded)','isolation','calves','','dumbbell,box',{rest:45,c:'On a step; drop the heels below the step.'}],
 ['sl-calf','Single-leg Calf Raise','isolation','calves','','box',{u:1,load:'bw+',rest:45,c:'One leg on a step; slow and full range.'}],
 ['tib-raise','Tibialis Raise','isolation','calves','','none',{load:'bw',rest:30,c:'Back to a wall; lift the toes as high as you can.'}],
 ['hip-abduction','Hip Abduction','isolation','glutes','','machine',{rest:45,c:'Lean forward slightly; push out and pause.'}],
 ['band-lateral-walk','Band Lateral Walk','isolation','glutes','quads','band',{load:'band',rest:30,c:'Band above the knees; stay low, steps stay wide.'}],
 ['clamshell','Clamshell','isolation','glutes','','band',{u:1,load:'band',rest:30,c:'Feet together, open the top knee; hips don’t roll back.'}],
 ['band-kickback','Band Glute Kickback','isolation','glutes','hamstrings','band',{u:1,load:'band',rest:30,c:'Kick straight back; no arching the lower back.'}],
 ['frog-pump','Frog Pump','isolation','glutes','','none',{load:'bw',rest:30,c:'Soles together; pump the hips up, chin tucked.'}],
 ['adductor-machine','Hip Adduction','isolation','glutes','','machine',{rest:45,c:'Squeeze the pads together; slow return.'}],
 ['copenhagen-plank','Copenhagen Plank','core','core','glutes','bench',{t:1,u:1,load:'bw',rest:45,c:'Top leg on the bench, squeeze it down; hips high.'}],
 // ---- core ----
 ['bird-dog','Bird Dog','core','core','glutes','none',{u:1,load:'bw',rest:30,c:'Opposite arm and leg; hips stay level, slow.'}],
 ['hanging-knee-raise','Hanging Knee Raise','core','core','forearms','pull-up-bar',{load:'bw',rest:45,alias:'knee raise,knee raises',c:'Knees to the chest, curl the pelvis up.'}],
 ['toes-to-bar','Toes-to-bar','core','core','lats,forearms','pull-up-bar',{load:'bw',rest:60,c:'Lat pull-down + hip flexion; toes touch the bar.'}],
 ['captains-chair','Captain’s Chair Leg Raise','core','core','','dip-station',{load:'bw',rest:45,alias:'leg raise (dip station)',c:'Forearms on the pads; raise legs, curl the hips.'}],
 ['l-sit','L-sit','core','core','triceps','dip-station',{t:1,load:'bw',rest:60,c:'Push down, legs straight out; hold.'}],
 ['v-up','V-up','core','core','','none',{load:'bw',rest:45,c:'Reach hands to feet, meet in the middle.'}],
 ['bicycle-crunch','Bicycle Crunch','core','core','','none',{load:'bw',rest:30,c:'Slow, opposite elbow to knee.'}],
 ['reverse-crunch','Reverse Crunch','core','core','','none',{load:'bw',rest:30,c:'Curl the pelvis off the floor; no swinging.'}],
 ['cable-crunch','Cable Crunch','core','core','','pulley',{rest:45,c:'Kneel; crunch the ribs to the hips.'}],
 ['woodchop','Cable Woodchop','core','core','','pulley',{u:1,rest:45,c:'Rotate from the torso; arms stay long.'}],
 ['band-woodchop','Band Woodchop','core','core','','band',{u:1,load:'band',rest:30,c:'Anchor high; chop diagonally across the body.'}],
 ['plank-shoulder-tap','Plank Shoulder Tap','core','core','front-delts','none',{load:'bw',rest:30,c:'Wide feet; tap without the hips rocking.'}],
 ['plank-reach','Plank Reach / Long-lever Plank','core','core','','none',{t:1,load:'bw',rest:45,c:'Elbows out past the head; squeeze glutes.'}],
 ['rkc-plank','RKC Plank','core','core','glutes','none',{t:1,load:'bw',rest:45,c:'Everything squeezed as hard as possible for 10–20 s.'}],
 ['stir-the-pot','Stir the Pot','core','core','front-delts','none',{t:1,load:'bw',rest:45,c:'Plank on a ball or the floor; small circles.'}],
 ['suitcase-hold','Suitcase Hold','core','core,forearms','','kettlebell',{t:1,u:1,rest:45,c:'Heavy bell in one hand; stand perfectly straight.'}],
 ['kb-windmill','KB Windmill','mobility','core','hamstrings,front-delts','kettlebell',{u:1,rest:60,c:'Bell overhead, hinge to the side; eyes on the bell.'}],
 ['ab-rollout-band','Band-assisted Ab Rollout','core','core','lats','ab-wheel,band',{load:'band',rest:60,c:'Band anchored behind you helps the return.'}],
 ['dragon-flag','Dragon Flag','core','core','lats','bench',{load:'bw',rest:90,c:'Body straight, lower slowly from the shoulders.'}],
 ['side-bend','Side Bend','core','core','','dumbbell',{u:1,rest:30,c:'One dumbbell; bend sideways and pull back up.'}],
 ['back-ext-45','45° Back Extension','hinge','glutes,hamstrings','core','machine',{load:'bw+',rest:60,c:'Round or flat back deliberately — glutes vs erectors.'}],
 ['superman','Superman Hold','core','core','glutes','none',{t:1,load:'bw',rest:30,c:'Lift arms and legs; hold, breathe.'}],
 // ---- carries & loaded conditioning ----
 ['kb-farmers-carry','KB Farmer’s Carry','carry','forearms,core','upper-back','kettlebell',{t:1,c:'Heavy bells, tall posture, quick short steps.'}],
 ['trap-bar-carry','Trap-bar Carry','carry','forearms,core','upper-back,quads','trap-bar',{t:1,c:'Load the bar; walk smooth, no leaning.'}],
 ['rack-carry','Front-rack Carry','carry','core','front-delts,forearms','kettlebell',{t:1,c:'Bells racked; ribs down, breathe behind the brace.'}],
 ['overhead-carry','Overhead Carry','carry','core,front-delts','forearms','kettlebell',{t:1,u:1,c:'Lock the elbow, pack the shoulder; walk.'}],
 ['bear-crawl','Bear Crawl','conditioning','core','front-delts,quads','none',{t:1,load:'bw',rest:45,c:'Knees an inch off the floor; opposite limbs.'}],
 ['sled-push','Sled Push','conditioning','quads,glutes','calves,core','sled',{t:1,c:'Arms locked, drive the legs, small fast steps.'}],
 ['sled-drag','Sled Drag','conditioning','hamstrings,glutes','core','sled',{t:1,c:'Walk backwards or forwards leaning into the strap.'}],
 ['med-ball-slam','Med Ball Slam','conditioning','core','lats,full-body','med-ball',{rest:45,c:'Reach tall, slam through the floor.'}],
 ['wall-ball','Wall Ball','conditioning','quads,glutes','front-delts','med-ball',{rest:60,c:'Squat, drive, throw to the target; catch and repeat.'}],
 ['box-jump','Box Jump','conditioning','quads,glutes','calves','box',{rest:60,c:'Land soft on the box, stand tall, step down.'}],
 ['broad-jump','Broad Jump','conditioning','glutes,quads','hamstrings','none',{load:'bw',rest:60,c:'Swing, jump, stick the landing.'}],
 ['kb-clean-press','KB Clean & Press','conditioning','full-body','front-delts,glutes','kettlebell',{u:1,rest:90,c:'Clean to the rack, press, lower, repeat.'}],
 ['kb-long-cycle','KB Long Cycle (2 bells)','conditioning','full-body','front-delts,glutes','kettlebell',{rest:90,c:'Double clean and jerk; pace yourself.'}],
 ['db-thruster','DB Thruster','conditioning','full-body','quads,front-delts','dumbbell',{rest:90,c:'Front squat straight into a press, one motion.'}],
 ['man-maker','Man Maker','conditioning','full-body','chest,upper-back','dumbbell',{rest:90,c:'Push-up, row each side, clean, press.'}],
 ['devils-press','Devil’s Press','conditioning','full-body','glutes,front-delts','dumbbell',{rest:90,c:'Burpee into a double-DB snatch.'}],
 ['bb-complex','Barbell Complex','conditioning','full-body','','barbell',{rest:120,c:'Row → clean → front squat → press → back squat, no rest.'}],
 ['power-clean','Power Clean','conditioning','full-body','glutes,upper-back','barbell',{rest:120,c:'Jump the bar up, catch it in the rack, hips above parallel.'}],
 ['hang-clean','Hang Clean','conditioning','full-body','glutes,upper-back','barbell',{rest:120,c:'From the hang; extend hard, catch high.'}],
 ['snatch','Snatch','conditioning','full-body','glutes,front-delts','barbell',{rest:150,c:'Wide grip; bar overhead in one movement.'}],
 ['db-snatch','DB Snatch','conditioning','full-body','glutes,front-delts','dumbbell',{u:1,rest:75,c:'Hinge, punch the dumbbell overhead in one motion.'}],
 ['battle-ropes','Battle Ropes','conditioning','full-body','front-delts,core','rope',{t:1,rest:45,c:'Alternating or double waves; sit into the hips.'}],
 ['stair-climb','Stair Climb','conditioning','quads,glutes','calves','stairs',{t:1,load:'none',rest:0,c:'Steady pace, breathe through the nose if you can.'}],
 ['run','Run','conditioning','full-body','calves,quads','none',{t:1,load:'none',rest:0,alias:'jog,jogging,running',c:'Easy pace = you can hold a conversation.'}],
 ['run-intervals','Running Intervals','conditioning','full-body','quads,calves','none',{t:1,load:'none',rest:60,c:'Hard effort, then walk/jog to recover.'}],
 ['hill-sprint','Hill Sprint','conditioning','glutes,hamstrings','calves','none',{t:1,load:'none',rest:90,c:'Short and steep; walk down for the rest.'}],
 ['bike','Stationary Bike','conditioning','quads','glutes','bike',{t:1,load:'none',rest:0,c:'Zone 2 or intervals — pick one per session.'}],
 ['bike-intervals','Bike Intervals','conditioning','quads','glutes','bike',{t:1,load:'none',rest:60,c:'Hard 30–60 s, easy 60–90 s.'}],
 ['treadmill-walk','Incline Treadmill Walk','conditioning','glutes,calves','quads','treadmill',{t:1,load:'none',rest:0,c:'12% incline, 5 km/h — no holding the rails.'}],
 ['swim','Swim','conditioning','full-body','lats,upper-back','none',{t:1,load:'none',rest:0,c:'Steady laps; long strokes.'}],
 ['shadow-boxing','Shadow Boxing','conditioning','full-body','front-delts,core','none',{t:1,load:'bw',rest:30,c:'Light on the feet; rounds of 2–3 min.'}],
 ['high-knees','High Knees','conditioning','quads,core','calves','none',{t:1,load:'bw',rest:30,c:'Fast feet, knees to hip height.'}],
 ['jumping-jack','Jumping Jacks','conditioning','full-body','calves','none',{t:1,load:'bw',rest:30,c:'Warm-up pace; land soft.'}],
 ['skipping-double','Double-unders','conditioning','calves','full-body','rope',{rest:30,c:'Higher jump, faster wrists — rope passes twice.'}],
 // ---- calisthenics / skills ----
 ['pull-up-hold','Chin-over-bar Hold','vertical-pull','lats,biceps','core','pull-up-bar',{t:1,load:'bw',rest:60,c:'Hold at the top; elbows down, chest up.'}],
 ['tuck-front-lever','Tuck Front Lever','core','lats,core','','pull-up-bar',{t:1,load:'bw',rest:60,c:'Straight arms, knees tucked, back parallel to the floor.'}],
 ['skin-the-cat','Skin the Cat','mobility','lats,core','front-delts','rings',{load:'bw',rest:60,c:'Roll through slowly; stop where the shoulders say stop.'}],
 ['handstand-hold','Wall Handstand Hold','vertical-push','front-delts','core,triceps','none',{t:1,load:'bw',rest:60,c:'Stacked hips over hands; push tall through the floor.'}],
 ['crow-pose','Crow Pose','core','core','front-delts,forearms','none',{t:1,load:'bw',rest:45,c:'Knees on the triceps; lean forward until the feet float.'}],
 ['wall-walk','Wall Walk','conditioning','front-delts','core,triceps','none',{load:'bw',rest:60,c:'Walk the feet up the wall and hands in; reverse out.'}],
 ['hollow-rock','Hollow Rock','core','core','','none',{load:'bw',rest:45,c:'Hold the hollow shape and rock; don’t break at the hips.'}],
 ['arch-hold','Arch / Superman Rock','core','core','glutes','none',{t:1,load:'bw',rest:30,c:'The opposite of hollow: everything up.'}],
 // ---- mobility & warm-up ----
 ['worlds-greatest','World’s Greatest Stretch','mobility','hamstrings,glutes','core','none',{u:1,load:'bw',rest:0,c:'Lunge, elbow to instep, rotate to the ceiling.'}],
 ['hip-90-90','90/90 Hip Switch','mobility','glutes','','none',{load:'bw',rest:0,c:'Both knees at 90°; switch sides without using the hands.'}],
 ['couch-stretch','Couch Stretch','mobility','quads','','none',{t:1,u:1,load:'bw',rest:0,c:'Back knee in the corner; squeeze the glute, tuck the pelvis.'}],
 ['pigeon','Pigeon Stretch','mobility','glutes','','none',{t:1,u:1,load:'bw',rest:0,c:'Shin across; hinge forward over the front leg.'}],
 ['hamstring-stretch','Hamstring Stretch','mobility','hamstrings','','none',{t:1,u:1,load:'bw',rest:0,c:'Flat back, hinge until you feel it — not until it hurts.'}],
 ['calf-stretch','Calf Stretch','mobility','calves','','none',{t:1,u:1,load:'bw',rest:0,c:'Heel down, knee straight; then bend the knee for the soleus.'}],
 ['ankle-rock','Ankle Dorsiflexion Rock','mobility','calves','','none',{u:1,load:'bw',rest:0,c:'Knee over the toes without the heel lifting.'}],
 ['deep-squat-hold','Deep Squat Hold','mobility','quads,glutes','core','none',{t:1,load:'bw',rest:0,c:'Sit in the bottom; push the knees out with the elbows.'}],
 ['cat-cow','Cat–Cow','mobility','core','','none',{load:'bw',rest:0,c:'Segment the spine; slow breathing.'}],
 ['thoracic-rotation','Thoracic Rotation (open book)','mobility','upper-back','','none',{u:1,load:'bw',rest:0,c:'Side-lying; rotate the top arm open, follow with the eyes.'}],
 ['thread-needle','Thread the Needle','mobility','upper-back','','none',{u:1,load:'bw',rest:0,c:'From all fours, reach under and through.'}],
 ['shoulder-dislocate','Band Shoulder Dislocates','mobility','front-delts,upper-back','','band',{load:'band',rest:0,c:'Wide grip; arms straight over and behind.'}],
 ['wall-slide','Wall Slide','mobility','upper-back','front-delts','none',{load:'bw',rest:0,c:'Back and arms on the wall; slide up without arching.'}],
 ['scap-pushup','Scapular Push-up','mobility','upper-back','chest','none',{load:'bw',rest:0,c:'Arms locked; only the shoulder blades move.'}],
 ['hip-circle','Hip CARs','mobility','glutes','core','none',{u:1,load:'bw',rest:0,c:'Slow, biggest possible circle at the hip.'}],
 ['shoulder-car','Shoulder CARs','mobility','front-delts','upper-back','none',{u:1,load:'bw',rest:0,c:'Slow full circle; ribs down, no leaning.'}],
 ['leg-swing','Leg Swings','mobility','hamstrings,glutes','','none',{u:1,load:'bw',rest:0,c:'Front-to-back then side-to-side; controlled.'}],
 ['inchworm','Inchworm','mobility','hamstrings','core','none',{load:'bw',rest:0,c:'Walk out to a plank, walk the feet back in.'}],
 ['spiderman-lunge','Spiderman Lunge','mobility','glutes,quads','core','none',{u:1,load:'bw',rest:0,c:'Long lunge; drop the same-side elbow inside the foot.'}],
 ['glute-bridge-march','Glute Bridge March','mobility','glutes','core','none',{load:'bw',rest:0,c:'Hold the bridge; lift one knee at a time, hips level.'}],
 ['band-dislocate-pull','Band Overhead Reach','mobility','front-delts','core','band',{load:'band',rest:0,c:'Ribs down; reach the band overhead and slightly back.'}],
 ['foam-roll','Foam Rolling','mobility','full-body','','foam-roller',{t:1,load:'none',rest:0,c:'Slow passes; pause on tender spots and breathe.'}],
 ['jefferson-curl','Jefferson Curl','mobility','hamstrings','core','dumbbell',{rest:45,c:'Round down one vertebra at a time with a light weight.'}],
 ['cossack-hold','Cossack Hold','mobility','glutes,quads','','none',{t:1,u:1,load:'bw',rest:0,c:'Sit deep to one side; other leg straight, toes up.'}],
 ['frog-stretch','Frog Stretch','mobility','glutes','','none',{t:1,load:'bw',rest:0,c:'Knees wide, rock gently back.'}],
 ['child-pose','Child’s Pose','mobility','upper-back','','none',{t:1,load:'bw',rest:0,c:'Reach long, breathe into the back.'}],
 ['down-dog','Downward Dog','mobility','hamstrings,calves','front-delts','none',{t:1,load:'bw',rest:0,c:'Push the floor away, heels reach down.'}],
 ['bretzel','Bretzel Stretch','mobility','quads,upper-back','','none',{t:1,u:1,load:'bw',rest:0,c:'Side-lying; top knee down, bottom foot pulled back, rotate open.'}],
 ['neck-mobility','Neck Circles / Nods','mobility','upper-back','','none',{load:'bw',rest:0,c:'Slow, small, pain-free range.'}],
 ['wrist-mobility','Wrist Circles & Rocks','mobility','forearms','','none',{load:'bw',rest:0,c:'On all fours; rock forward over the wrists.'}],
];
